### ISSUE TITLE
new version and name of msgpack (0.5.6)

### ISSUE THREAD

**Issue by hhromic** [AnacondaRecipes/msgpack-python-feedstock#1]
Hello,
`msgpack` is now in version `0.5.6`.
Also, the name/repository changed from `msgpack-python` to simply `msgpack` in PyPi [1].
Can this recipe be updated accordingly? Thanks!

[1] https://pypi.python.org/pypi/msgpack

**Comment by mingwandroid** [comment]
No, we provide more than python software and prefer the disambiguation of the `-python` suffix.

**Comment by kalefranz** [comment]
Perhaps once we have the bandwidth for https://github.com/conda/conda/issues/6939

**Comment by hhromic** [comment]
Hi, we are discussing this issue here:
https://github.com/conda-forge/msgpack-python-feedstock/issues/5

**Comment by willsALMANJ** [comment]
Keeping the conda package name as `msgpack-python` is okay, but can this package be updated so that `pip` recognizes the installed Python package as `msgpack` rather than `msgpack-python`? As it is now, if you have any package that requires `msgpack` installed, `pip` now complains that `msgpack` is not installed whenever you run a `pip install` command. To see this, try `conda create -n tmp distributed` and then activate the environment and try pip installing anything. The conda-forge recipe made this change here: https://github.com/conda-forge/msgpack-python-feedstock/pull/7

**Comment by jjhelmus** [comment]
@willsALMANJ This seems reasonable.  I've adjusted the recipe here to be more in line with conda-forge and built a new set of packages.  The msgpack 0.5.6 package with a build number of 1 has these modification and are recognized by pip as `msgpack`.

```
(msgpack_defaults) ~$ conda list msgpack
# packages in environment at /home/jhelmus/anaconda3/envs/msgpack_defaults:
#
# Name                    Version                   Build  Channel
msgpack-python            0.5.6            py36h6bb024c_1    defaults
(msgpack_defaults) ~$ pip list 
Package    Version  
---------- ---------
certifi    2018.4.16
msgpack    0.5.6    
pip        10.0.1   
setuptools 39.2.0   
wheel      0.31.1   
```
